// Mock data for Afroz Swift Financials

import type { Company, SaleActivityRow, Vendor, Customer, Product, ActivityRow } from '@/types';

export const companyData: Company = {
  name: 'The Demo Company (Pvt) Ltd',
  address: 'Office No 100, 1st Floor, ABC Building, XYZ Road, Lahore, Pakistan',
  phone: '+92 42 9876543',
  email: 'abcdefg@email.com',
  website: 'www.company.com',
  ntn: '1234567',
  salesTaxRegn: '4124-5135-246',
};

export const saleActivityData: SaleActivityRow[] = [
  {
    invoiceNo: 1,
    invoiceDate: '10-09-2021',
    cusCode: '120020007',
    customerName: 'The Best School Systems',
    invoiceType: 'Fed. Sales Tax Invoice',
    invoiceAmount: 2880,
    returns: 0,
    receipts: 2880,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 2880,
    balanceAmount: 0,
  },
  {
    invoiceNo: 1,
    invoiceDate: '20-02-2022',
    cusCode: '120020002',
    customerName: 'MSR Associates',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 86650,
    returns: 3600,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 3600,
    balanceAmount: 83050,
  },
  {
    invoiceNo: 2,
    invoiceDate: '23-08-2021',
    cusCode: '120020001',
    customerName: 'Star Enterprises',
    invoiceType: 'Fed. Sales Tax Invoice',
    invoiceAmount: 39912,
    returns: 0,
    receipts: 39912,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 39912,
    balanceAmount: 0,
  },
  {
    invoiceNo: 2,
    invoiceDate: '01-05-2022',
    cusCode: '120020002',
    customerName: 'MSR Associates',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 18000,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 18000,
  },
  {
    invoiceNo: 3,
    invoiceDate: '05-01-2022',
    cusCode: '120020004',
    customerName: 'Bismillah Traders',
    invoiceType: 'Fed. Sales Tax Invoice',
    invoiceAmount: 14400,
    returns: 1800,
    receipts: 12600,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 14400,
    balanceAmount: 0,
  },
  {
    invoiceNo: 3,
    invoiceDate: '08-06-2022',
    cusCode: '120020005',
    customerName: 'City Associates',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 93500,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 93500,
  },
  {
    invoiceNo: 4,
    invoiceDate: '22-04-2022',
    cusCode: '120020003',
    customerName: 'Khalid Brothers',
    invoiceType: 'Fed. Sales Tax Invoice',
    invoiceAmount: 57600,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 57600,
  },
  {
    invoiceNo: 4,
    invoiceDate: '10-06-2022',
    cusCode: '120020003',
    customerName: 'Khalid Brothers',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 18750,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 18750,
  },
  {
    invoiceNo: 5,
    invoiceDate: '03-06-2022',
    cusCode: '120020002',
    customerName: 'MSR Associates',
    invoiceType: 'Fed. Sales Tax Invoice',
    invoiceAmount: 3600,
    returns: 0,
    receipts: 3456,
    whtFedITax: 144,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 3600,
    balanceAmount: 0,
  },
  {
    invoiceNo: 5,
    invoiceDate: '05-06-2022',
    cusCode: '120020001',
    customerName: 'Star Enterprises',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 4032,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 4032,
  },
  {
    invoiceNo: 6,
    invoiceDate: '02-06-2022',
    cusCode: '120020004',
    customerName: 'Bismillah Traders',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 28800,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 28800,
  },
  {
    invoiceNo: 7,
    invoiceDate: '11-06-2022',
    cusCode: '120020004',
    customerName: 'Bismillah Traders',
    invoiceType: 'Non Tax Invoice',
    invoiceAmount: 72000,
    returns: 0,
    receipts: 0,
    whtFedITax: 0,
    whtFedSTax: 0,
    whtProvSTax: 0,
    discount: 0,
    totalCredited: 0,
    balanceAmount: 72000,
  },
];

export const vendorsData: Vendor[] = [
  {
    code: '210020001',
    name: 'STech Consultants',
    type: 'Local Vendors',
    address: 'Main Road, Karachi',
    contactPerson: '',
    contactNo: '32353467',
    email: '',
    creditTerms: '',
    creditDays: 0,
    creditLimit: 0,
  },
  {
    code: '210020002',
    name: 'Green Age Marketing',
    type: 'Local Vendors',
    address: 'G.T Road, Lahore',
    contactPerson: 'Ahmad Khan',
    contactNo: '3212345678',
    email: 'info@greenage.com',
    creditTerms: 'Net 30',
    creditDays: 30,
    creditLimit: 500000,
  },
  {
    code: '210020003',
    name: 'Pakistan Suppliers',
    type: 'Local Vendors',
    address: 'Industrial Area, Faisalabad',
    contactPerson: 'Ali Raza',
    contactNo: '3344556677',
    email: 'sales@pksuppliers.com',
    creditTerms: 'Net 15',
    creditDays: 15,
    creditLimit: 200000,
  },
  {
    code: '210020004',
    name: 'Global Traders',
    type: 'Import Vendors',
    address: 'Dubai, UAE',
    contactPerson: 'John Smith',
    contactNo: '+971501234567',
    email: 'john@globaltraders.ae',
    creditTerms: 'Net 60',
    creditDays: 60,
    creditLimit: 1000000,
  },
  {
    code: '210020005',
    name: 'Fast Logistics',
    type: 'Service Vendors',
    address: 'Karachi, Pakistan',
    contactPerson: 'Sarah Ahmed',
    contactNo: '3123456789',
    email: 'sarah@fastlogistics.pk',
    creditTerms: 'Net 7',
    creditDays: 7,
    creditLimit: 100000,
  },
];

export const customersData: Customer[] = [
  {
    code: '120020001',
    name: 'Star Enterprises',
    type: 'Local Customers',
    billingAddress: 'Main Road, Lahore',
    shippingAddress: 'Main Road, Lahore',
    contactPerson: 'Muhammad Ali',
    contactNo: '3212345678',
    email: 'ali@starenterprises.com',
    creditTerms: 'Net 30',
    creditDays: 30,
    creditLimit: 500000,
    region: 'Lahore',
    subRegion: 'Central',
    accountManager: 'Mr. Ahmad Khan',
  },
  {
    code: '120020002',
    name: 'MSR Associates',
    type: 'Local Customers',
    billingAddress: 'G.T Road, Gujranwala',
    shippingAddress: 'G.T Road, Gujranwala',
    contactPerson: 'Rashid Mehmood',
    contactNo: '3344556677',
    email: 'rashid@msr.com',
    creditTerms: 'Net 15',
    creditDays: 15,
    creditLimit: 300000,
    region: 'Gujranwala',
    subRegion: 'North',
    accountManager: 'Mr. Abid Rahman',
  },
  {
    code: '120020003',
    name: 'Khalid Brothers',
    type: 'Local Customers',
    billingAddress: 'Gul Haji Plaza, Peshawar',
    shippingAddress: 'Gul Haji Plaza, Peshawar',
    contactPerson: 'Khalid Ahmad Khan',
    contactNo: '05125125121',
    email: 'khalid@kb.com',
    creditTerms: 'Net 30',
    creditDays: 30,
    creditLimit: 400000,
    region: 'Peshawar',
    subRegion: 'West',
    accountManager: 'Mr. Abid Rahman',
  },
  {
    code: '120020004',
    name: 'Bismillah Traders',
    type: 'Local Customers',
    billingAddress: 'Main Road, Multan',
    shippingAddress: 'Main Road, Multan',
    contactPerson: 'Abdullah',
    contactNo: '3211122233',
    email: 'abdullah@bismillah.com',
    creditTerms: 'Net 7',
    creditDays: 7,
    creditLimit: 200000,
    region: 'Multan',
    subRegion: 'South',
    accountManager: 'Mr. Ahmad Khan',
  },
  {
    code: '120020005',
    name: 'City Associates',
    type: 'Local Customers',
    billingAddress: 'Defence Road, Karachi',
    shippingAddress: 'Defence Road, Karachi',
    contactPerson: 'Imran Khan',
    contactNo: '3122233344',
    email: 'imran@cityassoc.com',
    creditTerms: 'Net 45',
    creditDays: 45,
    creditLimit: 600000,
    region: 'Karachi',
    subRegion: 'South',
    accountManager: 'Mr. Abid Rahman',
  },
  {
    code: '120020006',
    name: 'The Best School Systems',
    type: 'Institutional Customers',
    billingAddress: 'Canal Road, Faisalabad',
    shippingAddress: 'Canal Road, Faisalabad',
    contactPerson: 'Principal Office',
    contactNo: '0411234567',
    email: 'info@tbss.edu.pk',
    creditTerms: 'Net 60',
    creditDays: 60,
    creditLimit: 800000,
    region: 'Faisalabad',
    subRegion: 'Central',
    accountManager: 'Mr. Ahmad Khan',
  },
  {
    code: '120020007',
    name: 'Tech Solutions Ltd',
    type: 'Corporate Customers',
    billingAddress: 'Software Technology Park, Islamabad',
    shippingAddress: 'Software Technology Park, Islamabad',
    contactPerson: 'CEO Office',
    contactNo: '0519876543',
    email: 'ceo@techsolutions.com',
    creditTerms: 'Net 30',
    creditDays: 30,
    creditLimit: 1000000,
    region: 'Islamabad',
    subRegion: 'Capital',
    accountManager: 'Mr. Abid Rahman',
  },
];

export const productsData: Product[] = [
  {
    code: '1001000008',
    name: 'Adams Cheese',
    category: 'Dairy',
    subCategory: 'Frozen',
    description: 'Premium quality cheese',
    unit: 'Pcs',
    pcsPerPack: 10,
    productCost: 1170.00,
    image: '/images/product-cheese.png',
  },
  {
    code: '1000000006',
    name: 'Sunsilk Shampoo',
    category: 'Personal Care',
    subCategory: 'Hair Care',
    description: 'Hair care shampoo',
    unit: 'Pcs',
    pcsPerPack: 12,
    productCost: 850.00,
    image: '/images/product-shampoo.png',
  },
  {
    code: '1002000012',
    name: 'Lemon Sandwich',
    category: 'Bakery',
    subCategory: 'Snacks',
    description: 'Lemon flavored sandwich biscuits',
    unit: 'Pcs',
    pcsPerPack: 24,
    productCost: 144.00,
    image: '/images/product-biscuit.png',
  },
  {
    code: '1003000045',
    name: 'Nestle Milk',
    category: 'Dairy',
    subCategory: 'Liquid',
    description: 'Fresh milk 1 liter',
    unit: 'Pcs',
    pcsPerPack: 12,
    productCost: 180.00,
    image: '/images/product-milk.png',
  },
  {
    code: '1004000078',
    name: 'Coca Cola',
    category: 'Beverages',
    subCategory: 'Soft Drinks',
    description: 'Soft drink 1.5 liter',
    unit: 'Pcs',
    pcsPerPack: 6,
    productCost: 120.00,
    image: '/images/product-cola.png',
  },
  {
    code: '1005000091',
    name: 'Lays Chips',
    category: 'Snacks',
    subCategory: 'Chips',
    description: 'Potato chips',
    unit: 'Pcs',
    pcsPerPack: 20,
    productCost: 50.00,
    image: '/images/product-chips.png',
  },
];

export const activityData: ActivityRow[] = [
  {
    documentNo: 'Sale Invoices (Non Tax) No. 7',
    partyName: 'Bismillah Traders',
    remarks: '',
    amount: 72000.00,
    status: 'Authorized',
    authorization: 'Authorized',
  },
];

export const dashboardSummary = {
  sales: {
    today: 0,
    previousDay: 0,
    monthTotal: 220682,
    total: 440124,
  },
  customers: {
    total: 1011838,
    dueNext7Days: { invoices: 4, amount: 177400 },
  },
  vendors: {
    total: 155879,
    dueNext1Day: { invoices: 2, amount: 101200 },
  },
  cashFlow: {
    previousBalance: { cash: 189835, bank: 1641449, total: 1831284 },
    receipts: { cash: 0, bank: 0, total: 0 },
    payments: { cash: 0, bank: 0, total: 0 },
    currentBalance: { cash: 189835, bank: 1641449, total: 1831284 },
  },
  postDatedCheques: {
    receivedFromCustomers: 0,
    issuedToVendors: 0,
  },
};

// Complete menu structure for Afroz Swift Financials
export const menuItems = [
  { 
    label: 'Management', 
    items: [
      { label: 'Dashboard', path: '/' },
      { label: 'Company Setup', path: '/company-setup' },
      { label: 'Financial Years', path: '/financial-years' },
      { label: 'User Logins', path: '/user-logins' },
      { label: 'User Rights', path: '/user-rights' },
      { label: 'Change Password', path: '/change-password' },
      { label: 'Software Preferences', path: '/preferences' },
    ] 
  },
  { 
    label: 'Lists', 
    items: [
      { label: 'Chart of Accounts', path: '/chart-of-accounts' },
      { label: 'Vendors', path: '/vendors' },
      { label: 'Vendor Types', path: '/vendor-types' },
      { label: 'Customers', path: '/customers' },
      { label: 'Customer Types', path: '/customer-types' },
      { label: 'Customer Regions', path: '/customer-regions' },
      { label: 'Customer Groups 1', path: '/customer-groups-1' },
      { label: 'Customer Groups 2', path: '/customer-groups-2' },
      { label: 'Products', path: '/products' },
      { label: 'Warehouses', path: '/warehouses' },
      { label: 'Services', path: '/services' },
      { label: 'Service Categories', path: '/service-categories' },
      { label: 'States/Province Tax Rates', path: '/states-tax-rates' },
      { label: 'Cost Centres', path: '/cost-centres' },
    ] 
  },
  { 
    label: 'Opening Balances',
    items: [
      { label: 'Accounts Opening Balances (Tax)', path: '/accounts-opening-balances-tax' },
      { label: 'Products Opening Balances (Tax)', path: '/products-opening-balances-tax' },
      { label: 'Accounts Opening Balances (Non-Tax)', path: '/accounts-opening-balances-nontax' },
      { label: 'Products Opening Balances (Non-Tax)', path: '/products-opening-balances-nontax' },
    ]
  },
  { 
    label: 'Purchases', 
    items: [
      { label: 'Purchase Orders', path: '/purchase-orders' },
      { label: 'Inwards Gate Passes', path: '/inwards-gate-passes' },
      { label: 'Goods Received Notes', path: '/goods-received-notes' },
      { label: 'Purchase Invoices', path: '/purchase-invoices' },
      { label: 'Purchase Returns', path: '/purchase-returns' },
    ] 
  },
  { 
    label: 'Sales (Tax)', 
    items: [
      { label: 'Quotations', path: '/quotations' },
      { label: 'Sale Orders', path: '/sale-orders' },
      { label: 'Sales Tax Invoices', path: '/sales-tax-invoices' },
      { label: 'Sale Returns', path: '/sale-returns' },
      { label: 'Quotations (Sales/Service)', path: '/sales-services-quotations' },
      { label: 'Sales/Service Orders', path: '/sales-services-orders' },
      { label: 'Sales/Services Rendered Tax Invoices', path: '/sales-services-rendered-tax-invoices' },
      { label: 'Sales/Services Rendered Tax Returns', path: '/sales-services-rendered-tax-returns' },
    ] 
  },
  { 
    label: 'Sales (Non-Tax)', 
    items: [
      { label: 'Quotations', path: '/quotations-nontax' },
      { label: 'Sale Orders', path: '/sale-orders-nontax' },
      { label: 'Sale Invoices', path: '/sale-invoices-nontax' },
      { label: 'Sale Returns', path: '/sale-returns-nontax' },
    ] 
  },
  { 
    label: 'Payments (Tax)', 
    items: [
      { label: 'Bank Payments to Vendors', path: '/bank-payments-vendors-tax' },
      { label: 'Bank Payments to Other Accounts', path: '/bank-payments-other-tax' },
      { label: 'Cash Payments to Vendors', path: '/cash-payments-vendors-tax' },
      { label: 'Cash Payments to Other Accounts', path: '/cash-payments-other-tax' },
    ] 
  },
  { 
    label: 'Payments (Non-Tax)', 
    items: [
      { label: 'Payments to Vendors', path: '/payments-vendors-nontax' },
      { label: 'Payments to Other Accounts', path: '/payments-other-nontax' },
      { label: 'Post Dated Cheques Issued', path: '/post-dated-cheques-issued' },
    ] 
  },
  { 
    label: 'Receipts', 
    items: [
      { label: 'Bank / Cash Receipts', path: '/receipts' },
    ] 
  },
  { 
    label: 'Adjustments', 
    items: [
      { label: 'Journal Vouchers', path: '/journal-vouchers' },
      { label: 'Stock Adjustments', path: '/stock-adjustments' },
    ] 
  },
  { 
    label: 'Store & Production',
    items: [
      { label: 'Inward Gate Passes', path: '/inwards-gate-passes' },
      { label: 'Goods Received Notes', path: '/goods-received-notes' },
      { label: 'Delivery Notes', path: '/delivery-notes' },
      { label: 'Outwards Gate Passes', path: '/outwards-gate-passes' },
      { label: 'Bill of Materials', path: '/bill-of-materials' },
      { label: 'Material Issue Notes', path: '/material-issue-notes' },
      { label: 'Production Notes', path: '/production-notes' },
      { label: 'Production and Assembly', path: '/production-and-assembly' },
      { label: 'Add Inventory Adjustments', path: '/add-inventory-adjustments' },
      { label: 'Reduce Inventory Adjustments', path: '/reduce-inventory-adjustments' },
      { label: 'Inventory Transfers', path: '/inventory-transfers' },
    ]
  },
  { 
    label: 'H.R.M.' 
  },
  { 
    label: 'Reports', 
    items: [
      { label: 'User Log Report', path: '/reports/user-log' },
      { label: 'General Journal Detail', path: '/reports/general-journal' },
      { label: 'Purchases Report', path: '/reports/purchases' },
      { label: 'Sales Report', path: '/reports/sales' },
      { label: 'Payments Report', path: '/payments' },
      { label: 'Receipts Report', path: '/receipts' },
      { label: 'Productions Report', path: '/production-notes' },
      { label: 'Product Serial Tracking', path: '/products' },
      { label: 'Products Ledgers', path: '/reports/products-ledgers' },
      { label: 'Products Activity Report', path: '/reports/sale-activity' },
      { label: 'Products Balances', path: '/reports/products-balances' },
      { label: 'Services Ledgers', path: '/services' },
      { label: 'Jobs/Projects Ledgers', path: '/accounts' },
      { label: 'Jobs/Project Summary', path: '/accounts' },
      { label: 'Account Ledgers', path: '/reports/account-ledgers' },
      { label: 'Account Balances', path: '/reports/account-balances' },
      { label: 'Income Statement', path: '/reports/income-statement' },
      { label: 'Balance Sheet', path: '/reports/balance-sheet' },
      { label: 'Day Summary', path: '/day-summary' },
      { label: 'Sales Analysis', path: '/sales-analysis' },
      { label: 'Inventory Status', path: '/inventory-status' },
      { label: 'Accounts Receivable', path: '/accounts-receivable' },
    ] 
  },
];

export const sidebarNavItems = [
  { id: 'home', label: 'Home', path: '/' },
  { id: 'day-summary', label: 'Day Summary', path: '/day-summary' },
  { id: 'sales-analysis', label: 'Sales Analysis', path: '/sales-analysis' },
  { id: 'inventory-status', label: 'Inventory Status', path: '/inventory-status' },
  { id: 'accounts-receivable', label: 'Accounts Receivable', path: '/accounts-receivable' },
  { id: 'reminders', label: 'Reminders & Notes', path: '/reminders' },
];

export const stateProvinces = [
  { name: 'Baluchistan', taxRegnNo: 'B1234567' },
  { name: 'Islamabad Capital Territory', taxRegnNo: '1234567' },
  { name: 'Khyber Pakhtunkhwa', taxRegnNo: 'K1234567' },
  { name: 'Punjab', taxRegnNo: 'P1234567' },
  { name: 'Sindh', taxRegnNo: 'S1234567' },
];
